spring:
  application:
    name: jwt-security-practice

  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security_practice?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdEZW1vU2VjcmV0S2V5Rm9ySFMyNTYxMjM0NTY3ODkw
    access-expiration-ms: 600000
    refresh-expiration-ms: 1200000

server:
  port: 8080